### ISSUE TITLE
Install or Permission issue

### ISSUE THREAD

**Issue by Tonelock2021** [45Drives/cockpit-file-sharing#1] opened 2021-06-22 23:07 UTC
Hello, 
Not sure if this is the correct place for this.
I installed cockpit-file-sharing on my newly genned Ubuntu server running Ubuntu 20.04.2 LTS. 
the samba file sharing is overlaid with the spinning 45Drives spinning logo and an error shows up "Can't load /etc/samba/smb.conf - run testparm to debug it"

smb.conf does exist  and I can edit it as sudo
testparm runs as sudo and has no issues or errors and samba works fine.

My user login to cockpit does have sudo privs and other items in cockpit do get elevated correctly.
perms on smb.conf
-rw-r--r-- 1 root root 9273 Jun 22 16:07 /etc/samba/smb.conf
I am not sure how to proceed.

  
![image](https://user-images.githubusercontent.com/86329144/123010662-e3b63100-d373-11eb-9800-f51672b58f9e.png)

**Comment by bkelly16** [comment] 2021-06-23 12:31
This module uses sambas net registry to store and retrieve configuration settings.
Add "registry = yes" to the global section
```
[global]
include = registry
```

**Comment by Tonelock2021** [comment] 2021-06-23 22:24
Thanks for the reply Bkelly16.
My smb.conf already has include=registry . I did try 'Add "registry = yes"' to the global section as suggested and as suspected it failed on testparm so I removed.
I did get to see a bit more of the error today, it reflects a perms error in that the cockpit admin is not acting as sudo, similar to when running testparm as non sudo . The Cockpit user is running "Administrative access" and the user has sudo privs and all seems to work on other modules within Cockpit.

![image](https://user-images.githubusercontent.com/86329144/123174639-46233600-d435-11eb-90d8-1af476ca4b2b.png)

this is the results of sudo testparm


`# Global parameters
[global]
        log file = /var/log/samba/log.%m
        logging = file
        map to guest = Bad User
        max log size = 1000
        netbios name = WAL-R330-2
        obey pam restrictions = Yes
        pam password change = Yes
        panic action = /usr/share/samba/panic-action %d
        passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
        passwd program = /usr/bin/passwd %u
        registry shares = Yes
        security = USER
        server role = standalone server
        server string = %h server (Samba, Ubuntu)
        unix password sync = Yes
        workgroup = WALECTRIC.LOCAL
        idmap config * : backend = tdb`

**Comment by muratgonul** [comment] 2021-06-24 19:19
I am having the exact same problem as ToneLock2021.
I was using the earlier version which was cockpit-samba-manager. I removed and reinstalled it while testing and that one is still working fine.
I am running on `Linux helios64 5.10.16-rockchip64 #21.02.2 SMP PREEMPT Sun Feb 14 21:35:01 CET 2021 aarch64`.

**Comment by Tonelock2021** [comment] 2021-06-24 23:24
That makes sense and seems to address the issue. I did edit my local samba-manager.js to match but it actually got a bit worse, but cockpit is all new to me

**Comment by bkelly16** [comment] 2021-06-25 13:54
Hey everyone,
@muratgonul nailed it, we were missing 'superuser:require". Pull request was merged this morning.
We are going through the rest of the module to verify the rest as intended.
Thank for the report and the fix !

**Closed** 2021-06-25 13:54 UTC

**Comment by Tonelock2021** [comment] 2021-06-26 23:43
Yes this is now working for me. The debian images were not updated so apt update cockpit-file-sharing did not work.
I did a git clone make install and a bit of clean up. so now time to play thanks all.
